### ISSUE TITLE
Can PP be set to a value greater than 1 in pretrain_13b_megatron_ds.sh ?

### ISSUE THREAD

**Issue by genggui001** [Azure/MS-AMP-Examples#19]
Can PP be set to a value greater than 1 in pretrain_13b_megatron_ds.sh ?

In msamp/deepspeed/runtime/zero/fp8_stage_1_and_2.py

         self.fp8_param_groups = []
         for pg in init_optimizer.param_groups:
             fp8_params = []
             hp_params = []
             for p in pg['params']:
                 if not p.requires_grad:
                     continue
                 if isinstance(p, ScalingTensor):
                     fp8_params.append(p)
                 else:
                     hp_params.append(p)
             self.fp8_param_groups.append(fp8_params)
             pg['params'] = hp_params

When I set pp to 4, I found that all params in a param_group are ScalingTensor, causing hp_params to become an empty array. Eventually, an error was generated in deepspeed/runtime/zero/stage_1_and_2.py

     # create a flat tensor aligned at the alignment boundary
     def flatten_dense_tensors_aligned(self, tensor_list, alignment):
         return self.flatten(align_dense_tensors(tensor_list, alignment))

Exception has occurred: RuntimeError
torch.cat(): expected a non-empty list of Tensors

**Comment by wkcn** [comment]
Thanks for pointing it out! It is a bug.

**Comment by tocean** [comment]
Hi @genggui001, I believe this issue has been resolved.
