### ISSUE TITLE
Swin-transformer compatibility issue with torch 2.0

### ISSUE THREAD

**Issue by guoshzhao** [Azure/MS-AMP-Examples#9]
**What's the issue, what's expected?**:
Torch does not support torch._six anymore, but we still used it.

**How to reproduce it?**:
```
sudo docker run -it -d --name=msamp --privileged --net=host --ipc=host --gpus=all nvcr.io/nvidia/pytorch:23.04-py3 bash
# clone MS-AMP-Examples
cd Swin-Transformer
sh run.sh tiny amp
```

**Log message or shapshot?**:
![image](https://github.com/Azure/MS-AMP-Examples/assets/25875482/c83a3e33-d6e8-4069-a373-699d774196dd)

**Additional information**:

**Comment by wkcn** [comment]
A solution: `inf = float('inf')`
